import os
import shutil
import json
from pathlib import Path

MC_VERSION_MAP = {
    "1.21.4": 46, "1.21.3": 42, "1.21.2": 42, "1.21.1": 34, "1.21": 34,
    "1.20.6": 32, "1.20.5": 32, "1.20.4": 22, "1.20.3": 22, "1.20.2": 18,
    "1.20.1": 15, "1.20": 15, "1.19.4": 13, "1.19.3": 12, "1.19.2": 9,
    "1.19.1": 9, "1.19": 9, "1.18.2": 8, "1.18.1": 8, "1.18": 8,
    "1.17.1": 7, "1.17": 7, "1.16.5": 6, "1.16.4": 6, "1.16.3": 6,
    "1.16.2": 6, "1.16.1": 5, "1.16": 5, "1.15.2": 5, "1.15.1": 5,
    "1.15": 5, "1.14.4": 4, "1.13.2": 4
}

def get_pack_format(mc_version_str):
    """バージョン文字列または直接指定された数値をpack_formatに変換する"""
    # ユーザーが数値を直接入れた場合
    if str(mc_version_str).isdigit():
        return int(mc_version_str)
    
    # 辞書から探す（見つからなければ 1.20.1 用の 15 にフォールバック）
    return MC_VERSION_MAP.get(str(mc_version_str).strip(), 15)

def create_mcmeta(dest_dir, pack_format):
    mcmeta_path = os.path.join(dest_dir, "pack.mcmeta")
    if os.path.exists(mcmeta_path):
        print(f"  [Info] 既存の pack.mcmeta を維持します: {mcmeta_path}")
        return

    data = {
        "pack": {
            "pack_format": pack_format,
            "description": "Generated by kemomctr"
        }
    }
    try:
        with open(mcmeta_path, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=4)
        print(f"  [作成] pack.mcmeta を生成しました (pack_format: {pack_format})")
    except Exception as e:
        print(f"  [エラー] pack.mcmeta の作成に失敗しました: {e}")

def merge_json_files(src_path, dest_path):
    try:
        with open(dest_path, 'r', encoding='utf-8') as f:
            dest_data = json.load(f)
    except (json.JSONDecodeError, FileNotFoundError):
        print(f"  既存ファイルの読み込み失敗(または新規): {dest_path.name} -> 新規作成として扱います")
        dest_data = {}

    try:
        with open(src_path, 'r', encoding='utf-8') as f:
            src_data = json.load(f)
        
        dest_data.update(src_data)

        with open(dest_path, 'w', encoding='utf-8') as f:
            json.dump(dest_data, f, indent=4, ensure_ascii=False)
        return True
    except Exception as e:
        print(f"  [マージ失敗] {src_path.name} の処理中にエラー: {e}")
        return False

def process_file(source_file, src_root, dest_path_root):
    path_parts = Path(source_file).parts
    try:
        if 'assets' in path_parts:
            assets_index = path_parts.index('assets')
            rel_path = Path(*path_parts[assets_index:])
        else:
            rel_path = Path(source_file).parent.relative_to(src_root) / source_file.name
    except ValueError:
        rel_path = Path(source_file).relative_to(src_root)

    target_file = dest_path_root / rel_path
    target_dir = target_file.parent

    try:
        os.makedirs(target_dir, exist_ok=True)
        if target_file.exists():
            success = merge_json_files(source_file, target_file)
            if success:
                print(f"  [統合] {rel_path} (既存 + 新規)")
                return 1
        else:
            shutil.copy2(source_file, target_file)
            print(f"  [新規] {rel_path}")
            return 1
    except Exception as e:
        print(f"  [失敗] {source_file} の処理中にエラー: {e}")
    return 0

def run_pack_maker(src_dir, dest_dir, include_en, mc_version):
    src_path = Path(src_dir)
    dest_path = Path(dest_dir)

    if not src_path.exists():
        print(f"エラー: ソースディレクトリが存在しません: {src_dir}")
        return
        
    pack_format = get_pack_format(mc_version)

    print(f"=== kemomctr: リソースパック構築モード (col) ===")
    print(f"収集元: {src_dir}\n保存先: {dest_dir}")
    print(f"指定バージョン: {mc_version} (pack_format: {pack_format})")
    print(f"英語ファイルの収集: {'有効' if include_en else '無効'}")

    count = 0
    for root, dirs, files in os.walk(src_path):
        if "ja_jp.json" in files:
            count += process_file(Path(root) / "ja_jp.json", src_path, dest_path)

        if include_en and "en_us.json" in files:
            count += process_file(Path(root) / "en_us.json", src_path, dest_path)

    print("-" * 30)
    print(f"完了: 合計 {count} 個のファイルを処理しました。")
    print("作成されたassetsフォルダとpack.mcmetaを選択しzip圧縮するとMinecraftで読み込めるリソースパックになります")
    if count > 0:
        create_mcmeta(dest_dir, pack_format)